Created composer.json
kamilabs/MoneyBirdApiBundle pull request #1
Opened 2017-02-02 12:06 UTC by Dsazz

2017-02-02 13:44 UTC, ama3ing commented on composer.json
> +           "Kamilabs\\MoneyBirdApiBundle": ""
I prefer Kami namespace

2017-02-02 13:44 UTC, ama3ing commented on composer.json
> +    "target-dir": "Kamilabs/MoneyBirdApiBundle"
Same here

2017-02-03 12:34 UTC, ama3ing requested changes
Don't forget to remove:

```.phpcomplete_extended/```

And ignore this please

2017-02-03 12:34 UTC, ama3ing commented on Tests/KamiMoneyBirdBundle.php
> +class PayumBundleTest extends \PHPUnit_Framework_TestCase
Payum? 🤣 

Call @makasim he will like this

2017-02-03 12:34 UTC, ama3ing commented on .phpcomplete_extended/phpcomplete_index
> +{"classes":{"Kami\\MoneyBirdApiBundle\\KamiMoneyBirdBundle":{"methods":{"modifier":{"public":{"0":"setContainer","1":"boot","2":"shutdown","3":"build","4":"getContainerExtension","5":"getParent","6":
This file shouldn't be here

2017-02-03 12:34 UTC, ama3ing commented on .phpcomplete_extended/index_cache
> +{'namespace_cache': {}, 'classname_cache': {}, 'methods_cache': {}, 'fqcn_classkey_cache': {}}
This file shouldn't be here

2017-02-03 12:38 UTC, makasim commented on Tests/KamiMoneyBirdBundle.php
> +class PayumBundleTest extends \PHPUnit_Framework_TestCase
👎

2017-02-03 12:40 UTC, ama3ing commented on Tests/KamiMoneyBirdBundle.php
> +class PayumBundleTest extends \PHPUnit_Framework_TestCase
You are getting copied, that's mean how awesome you are 🥇

2017-02-03 12:47 UTC, ama3ing commented on Tests/KamiMoneyBirdBundle.php
> +class PayumBundleTest extends \PHPUnit_Framework_TestCase
@Dsazz give credits to @makasim in this file.

2017-02-06 13:18 UTC, ama3ing approved these changes

2017-02-06 13:18 UTC, merged